language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm

before_script:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then echo "extension = memcached.so" >> /etc/hhvm/php.ini; fi;'
    - composer selfupdate
    - composer install --prefer-source

script: ./vendor/bin/phpunit
