language: php

php:
    - 5.6
    - hhvm
    - 7

before_script:
    -  if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
    - composer selfupdate
    - composer install --prefer-source

script: ./vendor/bin/phpunit
