language: php

php:
    - 5.6
    - hhvm
    - 7

before_script:
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer selfupdate
    - composer install --prefer-source

script: ./vendor/bin/phpunit
